apiVersion: apps/v1
kind: Deployment
metadata:
  name: filmapp
  labels:
    app: filmapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filmapp
  template:
    metadata:
      labels:
        app: filmapp
    spec:
      containers:
        - name: filmapp
          image: ofdengiz/filmapp:latest
          ports:
            - containerPort: 80
